# Generated by Django 4.2.1 on 2023-05-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=400, verbose_name="제목")),
                ("writer", models.CharField(max_length=40, verbose_name="작성자")),
                ("content", models.TextField(verbose_name="내용")),
                ("wdate", models.DateTimeField()),
                ("hit", models.IntegerField()),
                ("filename", models.CharField(max_length=200)),
            ],
        ),
    ]
