# Generated by Django 4.2.1 on 2023-05-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("writer", models.CharField(max_length=100)),
                ("contents", models.TextField()),
                ("wdate", models.DateTimeField()),
                ("hit", models.IntegerField(default=0)),
            ],
        ),
    ]
